language: python

cache: pip

python:
  - 3.8

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - cp testing/settings_local.py bhr_site/
  - psql -c 'create database bhr;' -U postgres

script:
  - python manage.py test -v 2
