version: '3'                                                                                                                                                                                                                                  
services:                                                                                                                                                                                                                                     
  mongodb:                                                                                                                                                                                                                                    
    image: mongo:3.4.24-xenial                                                                                                                                                                                                                
    volumes:                                                                                                                                                                                                                                  
      - ./storage/mongodb:/data/db:z

  redis:
    image: redis:alpine
    volumes:
      - ./storage/redis:/data:z

  hpfeeds3:
    image: stingar/hpfeeds3:1.9.1
    links:
      - mongodb:mongodb
    ports:
      - "10000:10000"

  mnemosyne:
    image: stingar/mnemosyne:1.9.1
    env_file:
      - ./config/sysconfig/mnemosyne.env
    links:
      - mongodb:mongodb
      - hpfeeds3:hpfeeds3

  chnserver:
    image: stingar/chn-server:1.9.1
    volumes:
      - ./config/collector:/etc/collector:z
      - ./storage/chnserver/sqlite:/opt/sqlite:z
      - ./certs:/etc/letsencrypt:z
    env_file:
      - ./config/sysconfig/chnserver.env
    links:
      - mongodb:mongodb
      - hpfeeds3:hpfeeds3
    ports:
      - "80:80"
      - "443:443"

  hpfeeds-logger:
    image: stingar/hpfeeds-logger:1.9.1
    volumes:
      - ./storage/hpfeeds-logs:/var/log/hpfeeds-logger:z
    env_file:
      - config/sysconfig/hpfeeds-logger.env
    links:
      - hpfeeds3:hpfeeds3
      - mongodb:mongodb
